LOAD DATA
REPLACE
INTO TABLE BRIDGE_MA_CO
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeMA        INTEGER EXTERNAL,
  NomMA       FILLER CHAR,
  CodeCO        INTEGER EXTERNAL,
  NomCO       FILLER CHAR,
  MatchType     CHAR,
  Confidence    INTEGER EXTERNAL,
  SourceNote    CHAR,
  ValidFrom     DATE "YYYY-MM-DD",
  ValidTo       DATE "YYYY-MM-DD",
  IsCurrent     INTEGER EXTERNAL
)
