CREATE TABLE ED_HistoriserPrix (
    CodeG NUMBER NOT NULL,
    DateDebPrix DATE NOT NULL,
    DateFinPrix DATE,
    PrixKM   NUMBER(8,2)  CHECK (PrixKM  > 0),
    PrixJour NUMBER(8,2)  CHECK (PrixJour> 0),
    PrixBase NUMBER(8,2)  CHECK (PrixBase> 0),
    CONSTRAINT pk_historiserprix PRIMARY KEY (CodeG, DateDebPrix),
    CONSTRAINT fk_hist_gamme FOREIGN KEY (CodeG) REFERENCES ED_GAMME(CodeG),
    CONSTRAINT ck_hist_dates CHECK (DateFinPrix IS NULL OR DateFinPrix >= DateDebPrix)
);

INSERT INTO ED_HistoriserPrix (CodeG, DateDebPrix, DateFinPrix, PrixKM, PrixJour, PrixBase)
SELECT
    CodeG,
    TO_DATE('2025-01-01', 'YYYY-MM-DD'),
    TO_DATE('2025-12-31', 'YYYY-MM-DD'),
    PrixKM,
    PrixJour,
    PrixBase
FROM ED_GAMME;

ALTER TABLE ED_GAMME DROP COLUMN PrixKM;
ALTER TABLE ED_GAMME DROP COLUMN PrixJour;
ALTER TABLE ED_GAMME DROP COLUMN PrixBase;


CREATE TABLE RESERVERSOC_NEW
(
  CodeSoc     CHAR(14)   NOT NULL,
  DateDebSoc  DATE       NOT NULL,
  CodeG       NUMBER     NOT NULL,
  CodeC       NUMBER     NOT NULL,
  DateFinSoc  DATE       NOT NULL,
  DateResaSoc DATE       NOT NULL,
  CONSTRAINT PK_RESERVERSOC_NEW
    PRIMARY KEY (CodeSoc, DateDebSoc, CodeG, CodeC),
  CONSTRAINT FK_RS_NEW_SOC
    FOREIGN KEY (CodeSoc) REFERENCES ED_SOCIETE(CodeSoc),
  CONSTRAINT FK_RS_NEW_GAM
    FOREIGN KEY (CodeG)   REFERENCES ED_GAMME(CodeG),
  CONSTRAINT FK_RS_NEW_CLI
    FOREIGN KEY (CodeC)   REFERENCES ED_CLIENT(CodeC),
  CONSTRAINT CHK_RS_NEW_DATES
    CHECK (DateFinSoc >= DateDebSoc AND DateDebSoc >= DateResaSoc)
);

INSERT INTO RESERVERSOC_NEW (CodeSoc, DateDebSoc, CodeG, CodeC, DateFinSoc, DateResaSoc)
SELECT
    ED_RESERVERSOC.CodeSoc,
    ED_RESERVERSOC.DateDebSoc,
    ED_RESERVERSOC.CodeG,
    ED_LOUER.CodeC,
    ED_RESERVERSOC.DateFinSoc,
    ED_RESERVERSOC.DateResaSoc
FROM ED_RESERVERSOC
JOIN ED_VEHICULE ON ED_RESERVERSOC.CodeG = ED_VEHICULE.CodeG
JOIN ED_LOUER ON ED_VEHICULE.NoImmat = ED_LOUER.NoImmat AND ED_RESERVERSOC.DateDebSoc = ED_LOUER.DateDebLoc
JOIN ED_CLIENT ON ED_LOUER.CodeC = ED_CLIENT.CodeC AND ED_RESERVERSOC.CodeSoc = ED_CLIENT.CodeSoc
WHERE NOT EXISTS (
  SELECT 1
  FROM ED_RESERVERPRIVE rp
  WHERE rp.CodeC      = ED_LOUER.CodeC
    AND rp.DateDebClt = ED_LOUER.DateDebLoc
    AND rp.CodeG      = ED_VEHICULE.CodeG
);

DROP TABLE ED_RESERVERSOC CASCADE CONSTRAINTS;

RENAME RESERVERSOC_NEW TO ED_RESERVERSOC;

EXIT