LOAD DATA
REPLACE
INTO TABLE ED_CLIENT
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeC INTEGER EXTERNAL,
  NomC CHAR,
  PrenomC CHAR,
  RueC CHAR,
  CPC CHAR,
  VilleC CHAR,
  RegionC CHAR,
  CodeSoc INTEGER EXTERNAL
)
