LOAD DATA
REPLACE
INTO TABLE ED_GAMME
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeG INTEGER EXTERNAL,
  NomG CHAR,
  PrixKM DECIMAL EXTERNAL,
  PrixJour DECIMAL EXTERNAL,
  PrixBase DECIMAL EXTERNAL
)
