LOAD DATA
REPLACE
INTO TABLE ED_LOUER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeC INTEGER EXTERNAL,
  NoImmat CHAR,
  DateDebLoc DATE "YYYY-MM-DD",
  DateFinLoc DATE "YYYY-MM-DD",
  KmDeb DECIMAL EXTERNAL,
  KmFin DECIMAL EXTERNAL
)
