LOAD DATA
REPLACE
INTO TABLE ED_MARQUE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeMA INTEGER EXTERNAL,
  NomMA CHAR,
  PaysMA CHAR,
  DateCreationMA DATE "YYYY-MM-DD"
)
