LOAD DATA
REPLACE
INTO TABLE ED_RESERVERSOC
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeSoc INTEGER EXTERNAL,
  DateDebSoc DATE "YYYY-MM-DD",
  CodeG INTEGER EXTERNAL,
  DateFinSoc DATE "YYYY-MM-DD",
  DateResaSoc DATE "YYYY-MM-DD"
)
