LOAD DATA
REPLACE
INTO TABLE ED_RESERVERPRIVE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeC INTEGER EXTERNAL,
  DateDebClt DATE "YYYY-MM-DD",
  CodeG INTEGER EXTERNAL,
  DateFinClt DATE "YYYY-MM-DD",
  DateResa DATE "YYYY-MM-DD"
)
