LOAD DATA
REPLACE
INTO TABLE ED_SOCIETE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeSoc INTEGER EXTERNAL,
  NomSoc CHAR,
  RueSoc CHAR,
  CPSoc CHAR,
  VilleSoc CHAR
)
