LOAD DATA
REPLACE
INTO TABLE ED_VEHICULE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  NoImmat CHAR,
  Modele CHAR,
  DateAchat DATE "YYYY-MM-DD",
  CodeG INTEGER EXTERNAL,
  CodeMA INTEGER EXTERNAL
)
