BEGIN
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, REFERENCES ON '||USER||'.'||t.table_name||' TO BOCHENTHEHANDSOME1';
    EXECUTE IMMEDIATE 'GRANT SELECT, REFERENCES ON '||USER||'.'||t.table_name||' TO BOCHENTHEHANDSOME2';
  END LOOP;
END;
/
