LOAD DATA
APPEND
INTO TABLE S1_CONSTRUCTEUR
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    CodeCO, 
    NomCO, 
    MaisonMere, 
    DatecreatCO DATE 'YYYY-MM-DD', 
    DateFinCO DATE 'YYYY-MM-DD', 
    CodeTY
)
