SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT 9

-- Drop tables in dependency order
BEGIN EXECUTE IMMEDIATE 'DROP TABLE S1_COUVRIR PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE S1_CONSTRUCTEUR PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE S1_SEGMENT PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE S1_TYPECO PURGE'; 
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END; 
/

-- TYPECO
CREATE TABLE S1_TYPECO (
  CodeTY NUMBER PRIMARY KEY,
  NomTY  VARCHAR2(50) NOT NULL
);

-- SEGMENT
CREATE TABLE S1_SEGMENT (
  CodeSE NUMBER PRIMARY KEY,
  NomSE  VARCHAR2(100) NOT NULL
);

-- CONSTRUCTEUR
CREATE TABLE S1_CONSTRUCTEUR (
  CodeCO      NUMBER PRIMARY KEY,
  NomCO       VARCHAR2(100) NOT NULL,
  MaisonMere  VARCHAR2(100),
  DatecreatCO DATE,
  DateFinCO   DATE,
  CodeTY      NUMBER NOT NULL REFERENCES S1_TYPECO(CodeTY)
);

-- COUVRIR
CREATE TABLE S1_COUVRIR (
  CodeSE NUMBER NOT NULL REFERENCES S1_SEGMENT(CodeSE),
  CodeTY NUMBER NOT NULL REFERENCES S1_TYPECO(CodeTY),
  CONSTRAINT PK_S1_COUVRIR PRIMARY KEY (CodeSE, CodeTY)
);


PROMPT S1 DDL completed.
EXIT
