LOAD DATA
APPEND
INTO TABLE S3_LOUER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
TRAILING NULLCOLS
(
  CodeC        INTEGER EXTERNAL,
  NoImmat      CHAR,
  DateDebLoc   DATE "YYYY-MM-DD",
  CodeAGDep    INTEGER EXTERNAL,
  DateFinLoc   DATE "YYYY-MM-DD",
  KmDeb        INTEGER EXTERNAL,
  KmFin        INTEGER EXTERNAL,
  CodeAgRet    INTEGER EXTERNAL
)
