LOAD DATA
APPEND
INTO TABLE S3_RESERVERSOC
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  CodeSoc      CHAR,
  DateDebSoc   DATE "YYYY-MM-DD",
  CodeG        INTEGER EXTERNAL,
  CodeAGDep    INTEGER EXTERNAL,
  DateFinSoc   DATE "YYYY-MM-DD",
  DateResaSoc  DATE "YYYY-MM-DD",
  CodeAgRet    INTEGER EXTERNAL
)
