SET DEFINE OFF
SET ECHO ON
SET FEEDBACK ON
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR  EXIT 9

-- Drop in dependency order
BEGIN EXECUTE IMMEDIATE 'DROP TABLE S4_CONCURRENCE PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/


-- Master: agencies
CREATE TABLE S4_CONCURRENCE (
  Source   VARCHAR2(30),
  CodeG    NUMBER NOT NULL,
  DateDebPrix   DATE  NOT NULL,
  DateFinPrix   DATE  NOT NULL,
  PrixKM   NUMBER(8,2)  CHECK (PrixKM  > 0),
  PrixJour NUMBER(8,2)  CHECK (PrixJour> 0),
  PrixBase NUMBER(8,2)  CHECK (PrixBase> 0)
);


PROMPT S4 DDL completed.
EXIT
