LOAD DATA
APPEND
INTO TABLE S4_CONCURRENCE
FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
    SOURCE,
    CODEG,
    DATEDEBPRIX DATE 'YYYY-MM-DD',
    DATEFINPRIX DATE 'YYYY-MM-DD',
    PRIXKM,
    PRIXJOUR,
    PRIXBASE
)